### ISSUE TITLE
how to mock private func

### ISSUE THREAD

**Issue by soldiershen** [bouk/monkey#7]
the framework is great.
I am blocked when mocking private func.Check code below:
**src code:**
func C(){
	obj:=&ObjHasPrivateF{}
	obj.b()
}

type ObjHasPrivateF struct{

}

func(this *ObjHasPrivateF)b(){
	fmt.Println("b")
}

**Test code:**
func TestC(t *testing.T){
	var patchModelObjHasPrivateF *ObjHasPrivateF
	monkey.PatchInstanceMethod(reflect.TypeOf(patchModelObjHasPrivateF),"b",func(_ *ObjHasPrivateF){
		fmt.Println("cccc")
	})
	C()
	monkey.UnpatchAll()
}

result:
/usr/local/go/bin/go test -v jvmgo/monkey_test_private -run ^TestC$ -gcflags=-l
panic: unkown method b [recovered]
	panic: unkown method b

goroutine 5 [running]:
panic(0x2867a0, 0xc4200197b0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
testing.tRunner.func1(0xc420094180)
	/usr/local/go/src/testing/testing.go:579 +0x25d
panic(0x2867a0, 0xc4200197b0)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/bouk/monkey.PatchInstanceMethod(0x423e40, 0x299160, 0x2e987a, 0x1, 0x285460, 0x30e1b0, 0xc40a0fdc50)
	/Users/jieshe/Desktop/develop/go-lib/src/github.com/bouk/monkey/monkey.go:59 +0x32d
jvmgo/monkey_test_private.TestC(0xc420094180)
	/Users/jieshe/Desktop/develop/go-project/src/jvmgo/monkey_test_private/monkeys_private_test.go:24 +0x7f
testing.tRunner(0xc420094180, 0x30e1b8)
	/usr/local/go/src/testing/testing.go:610 +0x81
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:646 +0x2ec
exit status 2

if I change the func "b()" to "B()" monkey mocks it successfully.

**Comment by btfak** [comment]
source code use MethodByName to call method,it just not support private func

**Comment by soldiershen** [comment]
@btfak  I even use this monkey to mock my funcs but got block by this unsupport
